_home:
    path:  /
    defaults: { _controller: JmenaVentasBundle:Default:index }

_stock:
    path: /producto/stock
    defaults: { _controller: JmenaVentasBundle:Producto:stock }

_producto:
    path: /producto
    defaults: { _controller: JmenaVentasBundle:Producto:index }
_newProducto:
    path: /producto/new
    defaults: { _controller: JmenaVentasBundle:Producto:create }

_categoria:
    path: /categoria
    defaults: { _controller: JmenaVentasBundle:Categoria:index }
_newCategoria:
    path: /categoria/new
    defaults: { _controller: JmenaVentasBundle:Categoria:create }

_marca:
    path: /marca
    defaults: { _controller: JmenaVentasBundle:Marca:index }
_newMarca:
    path: /marca/new
    defaults: { _controller: JmenaVentasBundle:Marca:create }

_buscar:
    path: /resultado
    defaults: { _controller: JmenaVentasBundle:Default:buscarProducto }
    requirements:
        _method:  POST

_vender:
    path: /vender
    defaults: { _controller: JmenaVentasBundle:Default:venta }
    requirements:
        _method:  POST

_vendedor:
    path: /_vendedor
    defaults: { _controller: JmenaVentasBundle:Vendedor:index }