<?php

namespace Jmena\VentasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VendedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendedorRepository extends EntityRepository
{
}
